spring.application.name=SatGuard
server.port=${PORT:8080}

# ===================================================================
# CONFIGURACAO DE BANCO DE DADOS H2 (Para Testes e Avaliacao Local)
# ===================================================================
spring.datasource.url=jdbc:h2:mem:satguarddb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===================================================================
# CONFIGURACAO ORACLE (Descomente se for rodar no banco real da FIAP)
# ===================================================================
# spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
# spring.datasource.username=rmXXXXX
# spring.datasource.password=XXXXX
# spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# ===================================================================
# HIBERNATE & JPA
# ===================================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# SEGURANCA JWT
# ===================================================================
api.security.token.secret=chave-super-secreta-satguard-2026
